const { ACTION_IDENTITY } = require('kingly')

module.exports = {
  YED_SHALLOW_HISTORY_STATE: "H",
  YED_DEEP_HISTORY_STATE: "H*",
 STATE_LABEL_SEP : 'ღ',
 YED_LABEL_DECODE_SEP : 'ღ',
 DEFAULT_ACTION_FACTORY_STR : 'ACTION_IDENTITY',
 DEFAULT_ACTION_FACTORY : ACTION_IDENTITY,
 YED_ENTRY_STATE : 'init'
}
